### PR TITLE
patch/source_policy_documents

### PR DESCRIPTION
**Pull request by jd4883**
## what
* revises 'source_json' to 'source_policy_documents'. All references are adjusted to list notation as expected by terraform.
* revises 'override_json' to 'override_policy_documents'. All references are adjusted to list notation as expected by terraform.
* This change addresses the warning 'Warning: Argument is deprecated, Use the attribute "source_policy_documents" instead' warning, along with `Warning: Argument is deprecated, Use the attribute "override_policy_documents" instead.'

## why
* The proposed changes satiate what the AWS provider expects on more recent versions and will clear related warning messages.

### CODE REVIEW

**Comment by jd4883** [comment]
Bumping this thread, the proposed changes are clean and will prevent terraform from warning when making plans if using current provider versions. I'm happy to revise the code proposed if there is a functional reason to do so but please do review so myself and other users can enjoy using this module while not having to worry about provider warnings. Thanks in advance

**Comment by Gowiem** [comment]
@jd4883 can you confirm what AWS provider version added `source_policy_documents` + `override_policy_documents` so we can ensure we don't need to bump the AWS provider version pinning as part of this PR?

**Comment by jd4883** [comment]
Hi @Gowiem, thanks for taking a look. I did some poking around the AWS provider docs and it seems that `source_policy_documents` and `override_policy_documents` came into being in `3.28.0`. See docs here:
* [3.27](https://registry.terraform.io/providers/hashicorp/aws/3.27.0/docs/data-sources/iam_policy_document)
* [3.28](https://registry.terraform.io/providers/hashicorp/aws/3.28.0/docs/data-sources/iam_policy_document)

I could be wrong but the warning I believe came in as part of 4.0, I suspect when 5.0 rolls around, `source_policy_documents` and `override_policy_documents` will be required and the warning will become an error.

Let me know if there is any other info I can provide to get the proposed changes patched in.

Kind regards,

Jacob

**Comment by jd4883** [comment]
Greetings @Gowiem, its been 21 days since I provided the requested info, can this be finalized and implemented so that my team can leverage this updated module without receiving syntax warnings? As I understand it all info needed is here and you should be able to make whatever version constraints will be needed to ensure consistent functionality with this module.

**Comment by Gowiem** [comment]
@jd4883 thanks and apologies for missing your mentions (we get a but load of emails as part of maintaining 170 modules, so it happens often). 

Let's bump the AWS provider version to be `>= 3.28.0` so that we know that all consumers of this module will be able to use these new arguments. Do that and I'll give it a final review before we get it merged.

**Comment by jd4883** [comment]
@Gowiem the requested change has been added to the PR and it should be good to go

**Comment by Nuru** [comment]
@jd4883 Thank you for this PR and our apologies for the slow response. I am inclined to leave the warnings and archive this module, because the module can be completely and easily replaced. Change

```hcl
module "aggregated_policy" {
  source  = "cloudposse/iam-policy-document-aggregator/aws"
  version = "0.8.0"

  source_documents = [
    data.aws_iam_policy_document.base.json,
    data.aws_iam_policy_document.resource_full_access.json
  ]
}
```

With

```hcl
data "aws_iam_policy_document" "aggregated" {
  override_policy_documents = [
    data.aws_iam_policy_document.base.json,
    data.aws_iam_policy_document.resource_full_access.json
  ]
}
```

If you still want to preserve this module, please revise your PR to use just one data source.

**Comment by jd4883** [comment]
@Nuru I suppose archiving it makes sense in this case given the functionality is natively possible with the AWS provider. Thanks for the clear example and explanation.

**Comment by Firefishy** [comment]
As an outsider, it would he great if the README.md included the native replacement syntax before this module was archived.

**Comment by Gowiem** [comment]
Thanks @Nuru for spotting this module is no longer necessary. I was suspicious of that due to the nature of the changes, but don't use this module so just assumed there was still a need.

@jd4883 thanks for your contribution and friendly ping. Sorry it didn't end up needing to be necessary, but hopefully the approach provided is a less complex path for your org to move forward 👍

@Firefishy Great idea on putting that in the README -- I'll put up a PR for that now. 

Closing this PR out since it seems we've come to consensus on path forward here. Thanks folks!

**Pull request closed without merging**
